canonical/notary

.github/dependabot.yml
Adds dependency groupping and uses weekly schedule in dependabot
=> chore: Adds dependency groupping and uses weekly schedule in dependabot

internal/api/handlers.go, internal/api/handlers_test.go, internal/certdb/certdb.go
- Adds Get and Get by ID handlers
- Adds Post handler
- Adds tests
- Improves response codes when resource is not found
=> feat: Handlers to create and fetch accounts

internal/api/handlers.go, internal/api/handlers_test.go
Handles DELETE requests on the /accounts/{id} endpoint
=> feat: Adds handlers for DELETE for user accounts

ui/src/app/login.tsx, ui/src/app/nav.tsx
This change lets users log out of their account in the gocert frontend
=> feat: logout button

.github/ISSUE_TEMPLATE/enhancement_proposal.yaml
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> feat: enhancement proposal issue type

README.md
Improve the README.md by:
- Adding API documentation
- Re-structuring categories in
- Installation
- Configuration
- API
And we are moving the installation to the top as this is typically the first things users are looking for.
=> docs: add api documentation

snap/snapcraft.yaml
Improve snap documentation:
- Add Apache 2.0 license
- Add issues and source code links
=> docs: add links to snap documentation

.github/workflows/frontend-build.yaml, .github/workflows/frontend-unittest.yaml, .github/workflows/go-build.yaml, .github/workflows/go-lint.yaml, .github/workflows/go-unittest.yaml, .github/workflows/go-vet.yaml, .github/workflows/main.yml, .github/workflows/pr-lint.yml, .github/workflows/rock-build.yaml, .github/workflows/rock-publish.yaml, .github/workflows/rock-scan.yaml, .github/workflows/snap-build.yaml, .github/workflows/snap-publish.yaml
Rename workflow files using the following semantics `<technology>-<action>`. Ex:
- `go-build`
- `go-lint`
- `snap-build`
The workflow file names were all over the place and this change makes it easier to navigate.
=> chore: rename workflow files

ui/package-lock.json, ui/package.json, ui/src/app/certificate_requests/asideForm.tsx, ui/src/app/certificate_requests/components.tsx, ui/src/app/certificate_requests/page.tsx, ui/src/app/certificate_requests/table.test.tsx, ui/src/app/certificate_requests/table.tsx, ui/src/app/initialize/page.tsx, ui/src/app/login/page.tsx, ui/src/app/nav.tsx, ui/src/app/users/asideForm.tsx, ui/src/app/users/components.tsx, ui/src/app/users/page.tsx, ui/src/app/users/table.tsx
This PR removes the old `react-query` package and replaces it with the newer `@tanstack/react-query` package.
=> feat: upgrade from react query v3 to v5

internal/server/handlers_accounts.go, internal/server/handlers_accounts_test.go
Fixes an internal server error when receiving a GET for `/account/me`.
=> fix: Fix internal server error on /account/me

internal/db/db_certificates.go, internal/db/db_certificates_test.go, internal/db/db_csrs.go, internal/db/db_csrs_test.go, internal/db/db_users.go, internal/db/db_users_test.go, internal/db/validation.go
Improvements to constraints in db_users:
- Username can't be empty
- Password can't be empty
- Permission can't be other than 0 or 1
Improvements in db_certificates:
- Fixes the name of `DeleteCertificate` it was mistakenly named `DeleteCertificateRequestByCSR`
- `GetCertificateChain` expects `Certificate` objects not `CertificateRequestWithChain`
- The mapping between the values returned from the `getCertificateChainStmt` won't match the fields in the `Certificate` object if the `private_key_id` is not queried.
Improvements in db_csrs.go:
- Fixes naming mismatches in docstrings
- Fixes docstring of `DeleteCertificateRequest`
Test improvements:
- Tests edge cases and error states of `CreateUser`, `GetUser`, `UpdatePassword` and `DeleteUser` in `db_users_test`
- Test edge cases and error …
=> chore: Improves testing of edge cases and error states

.github/workflows/rock-test.yaml
=> fix: Fix failing rock test

.github/workflows/rock-build.yaml, .github/workflows/rock-publish.yaml, .github/workflows/rock-scan.yaml, .github/workflows/rock-test.yaml
This PR adds arm64 support to the rock.
=> feat: Build the rock for arm64 and amd64

internal/db/db_users.go, internal/server/handlers_helpers_test.go, internal/server/handlers_login_test.go, internal/server/server_test.go
There were a couple of unnecessary conversions in the code base, both in tests and actual source. Here we remove those conversions.
=> chore: remove unnecessary conversions

.github/workflows/main.yml, .github/workflows/tics.yaml
This change adds automatic tics reporting to notary.
[working run example](https://github.com/canonical/notary/actions/runs/14727930729/job/41334999267).
=> feat: add tics flow

docs/reference/config_file.md
This change includes a bunch of random issues I've found in the project while setting up the charm.
=> docs: fix logging config option

CONTRIBUTING.md
Notary won't start without this entry.
=> docs: Add (required) logging to the sample config file

ui/src/app/(notary)/certificate_authorities/components.tsx, ui/src/app/(notary)/certificate_authorities/table.tsx, ui/src/app/(notary)/certificate_requests/components.tsx, ui/src/app/(notary)/certificate_requests/table.tsx, ui/src/components/NotaryAppNavigationBars.tsx
Given disabled buttons, when users were clicking them, they would behave as if they were enabled. This bug is addressed here by using OnClick instead of OnMouseDown.
Fixes #102
=> fix: make disabled buttons unclickable [ui]

docs/how-to/deploy.md, docs/tutorials/getting_started.md
Now that we have a 0.0 track for Notary, point users to using the track instead of `latest`. Even though it's still an early project, I want to introduce to best practice to use tracks asap to avoid having users receive breaking changes on latest down the line. 
- https://snapcraft.io/notary
=> docs: use 0.0 track to deploy notary

.github/workflows/release-please.yaml
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> feat(workflows): add release please workflow
