.github/workflows/build-rock.yaml
rockcraft.yaml

Bump the build base to Ubuntu 24.04. Here we also need to include the base-files_lib slice because starting Ubuntu 24.04, the 'base-files' package provides "bin" as a symlink to "usr/bin".

chore: use ubuntu 24.04 build base

---

internal/api/handlers.go
internal/api/middleware.go
internal/api/middleware_test.go
internal/certdb/validation.go
internal/metrics/metrics.go
internal/metrics/metrics_test.go

This change introduces the collection of metrics for GoCert. These metrics are the ones described in the GoCert backend specification, and two metrics specific to the webserver: Total number of requests and Request Latency.
There are 2 main methods of collecting these metrics: 
* As middleware that can sit between the endpoint handlers and the request and responses, and record anything that happens.
* As a separate goroutine that periodically queries the DB to update the metrics.
There are pros and cons to doing either.
For the middleware method, the main pro is that there is visibility to every process the webserver does, whether that's auth, logs, or anything in the request and response objects. This is nice for collecting information about the webserver, like number of failed logins, …

feat: Expose certificate metrics

---

.github/workflows/build-rock.yaml
.github/workflows/publish-rock.yaml
.github/workflows/scan-rock.yaml
CONTRIBUTING.md

Use skopeo from rockcraft. This addresses an issue where we were not able to copy the built OCI image to docker images. The skopeo version in the snap dates from 2019 (v1.13.3) as the one in rockcraft is more recent (v1.14.2)
```
time="2024-06-14T18:40:29Z" level=fatal msg="writing blob: io: read/write on closed pipe"
```
- https://github.com/canonical/rockcraft/pull/477

chore: use skopeo from rockcraft

---

cmd/gocert/main.go
cmd/gocert/main_test.go
internal/api/server.go
internal/api/server_test.go
internal/config/config.go
internal/config/config_test.go

This PR does two things:
1. Add validation that all keys are in the configuration file. For example, if you did not specify the `cert_path` key, you would receive a `no such file or directory` error because the program was trying to use the file name "" (empty string) for the certificate. Now we return an error saying that the `cert_path` is missing. 
2. Move configuration management to its own isolated place under `internal/config`. This allows to write tests specifically for configuration and decouple configuration from the HTTP server.

fix: add key missing in config validation

---

internal/api/middleware.go

Here we improve logging in GoCert addressing two issues. One relates to quality and the other to quantity.
The status code in logs used to always be `200` even if the real returned status code was something else. Here we fix this and display the accurate status code.
```
2024/06/14 16:35:16 error: given csr already recorded
2024/06/14 16:35:16 POST /api/v1/certificate_requests 200 OK
```
```
2024/06/14 16:33:59 error: given csr already recorded
2024/06/14 16:33:59 POST /api/v1/certificate_requests 400 Bad Request
```
We get rid of logging for http calls made to static javascript files. For every refresh on the certificate requests table, this reduces the number of logs from 11 to 2, making logs much easier to parse. 
```
2024/06/14 16:09:10 GET /certificate_requests.html 200 OK
2024/06/14 …
```

fix: display accurate status code in logs

---

ui/src/app/certificate_requests/row.test.tsx
ui/src/app/certificate_requests/row.tsx
ui/src/app/certificate_requests/table.test.tsx
ui/src/app/utils.ts

- Improves the code to extract certificates
- Improves the code to compare certificates
- Display certificate details
Both certificate and csr details are displayed, as there is no guarantee that those are equal.
Discrepancies between csr and cert fields are highlighted in red.
The details are responsive and they go into one column on small screens.
The expiry date is coloured green, it turns red when we are within one day into expiry and beyond.

feat: Extract certificate details

---

internal/api/handlers.go
internal/api/handlers_test.go
internal/certdb/certdb.go

- Adds an endpoint and handlers to change user account password
- Adds test cases

feat: Adds an endpoint and handlers to change user account password

---

internal/api/handlers.go
internal/api/handlers_test.go

There are 2 changes that did not make it to the users handlers PR's that have been added here:
added a message including the length of the password required
dont return pw if we already sent one

chore: error messages and only returning generated passwords

---

.github/workflows/build-rock.yaml
internal/api/handlers.go
internal/api/handlers_test.go
internal/api/middleware.go
internal/api/server.go

This PR implements the authentication and permission functionality described in TE091. The `/metrics` and `/status` endpoints are left unauthenticated, as well as the first POST request to the `api/v1/accounts` endpoint. For more details, please read TE091.

feat: authentication middleware for the GoCert server

---

ui/package-lock.json
ui/package.json
ui/src/app/aside.tsx
ui/src/app/auth/authContext.tsx
ui/src/app/certificate_requests/components.tsx
ui/src/app/certificate_requests/page.tsx
ui/src/app/certificate_requests/row.tsx
ui/src/app/certificate_requests/table.tsx
ui/src/app/globals.scss
ui/src/app/layout.tsx
ui/src/app/login.tsx
ui/src/app/login/page.tsx
ui/src/app/nav.test.tsx
ui/src/app/nav.tsx
ui/src/app/queries.ts
ui/src/app/types.ts
ui/src/app/utils.ts

This change introduces the functionality to log in to GoCert. You will have to create an account using the API at first.
Users are redirected to the login page if they are not logged in. Once logged in, your user account appears as a button in the bottom left.

feat: logging in to GoCert

---

internal/api/handlers.go
internal/api/handlers_test.go
internal/api/middleware.go

This PR has 2 changes:
`Initialized` means the first admin user has been created for GoCert.
The reason to report this in status is because gocert behaves differently in a subtle way when it hasn't been initialized, namely the fact that no authentication is needed to create this first account. Clients including the frontend need a stable way to query for this information, and the status endpoint is a good place to report it.
We previously blocked any `Delete` request to the user with the ID of 1 to prevent users from deleting the admin account. The issue with this is the fact that the user with account ID 1 may not always be the admin account.
While this assumption is true for the current GoCert, it may not remain true when different auth methods and database connectors are added in the …

chore: better admin delete protection & more info in the status endpoint

---

ui/src/app/auth/authContext.tsx
ui/src/app/change_password/page.tsx
ui/src/app/login.tsx
ui/src/app/nav.test.tsx
ui/src/app/queries.ts
ui/src/app/types.ts
ui/src/app/utils.ts

This change lets users change their account password

feat: change password form

---

ui/src/app/auth/authContext.tsx
ui/src/app/initialize/page.tsx
ui/src/app/login/page.tsx
ui/src/app/nav.tsx
ui/src/app/onboarding/page.tsx
ui/src/app/queries.ts
ui/src/app/types.ts
ui/src/app/users/asideForm.tsx

This change includes an onboarding flow for when a user connects to the frontend of an uninitialized GoCert application. This page can in the future include a place to upload a signing CA certificate or have GoCert autogenerate one.

feat: onboarding flow for the frontend

---

ui/src/app/login/page.tsx

This PR adds the requested enhancements and closes #47.

chore: better login page

---

internal/api/handlers.go
ui/src/app/page.tsx

This PR moves the redirect mechanism from the backend to the frontend, which is a bit cleaner and fixes a bug where any url that ends with a slash (like `/users/` or `/alkshflgeh/`) redirects to the certificate_requests page.

refactor: redirect page in the frontend

---

.github/workflows/build-rock.yaml
CONTRIBUTING.md
README.md
rockcraft.yaml

This PR improves the documentation so that following all of the commands in the readme results in a working application.

chore: more detailed docs

---

ui/src/app/certificate_requests/asideForm.tsx
ui/src/app/queries.ts

This change fixes #34 by properly handling returned errors and placing them in the form.

fix: properly handle errors when posting CSR's

---

cmd/gocert/main.go
cmd/gocert/main_test.go

Logging to stderr does not show up in pebble. This change makes Gocert log to stdout. Probably fixes #56

fix: log to stdout

---

.github/workflows/build-rock.yaml
internal/api/handlers_test.go
internal/certdb/certdb.go
internal/certdb/certdb_test.go
internal/certdb/validation.go
internal/certdb/validation_test.go
internal/metrics/metrics_test.go
ui/src/app/certificate_requests/components.tsx
ui/src/app/certificate_requests/row.tsx
ui/src/app/utils.ts

This PR adds the change required to accept and distribute issuer certificates alongside the certificate of the CSR. A new certificate must contain a bundle of at least 2 certificates in a valid chain to be accepted. Any extra characters will be ignored.

feat!: accept bundles instead of just certificates

---

.github/workflows/build-snap.yaml
.github/workflows/main.yml
.github/workflows/publish-snap.yaml
README.md
notary.yaml
service/bin/notaryd-start
service/notary.yaml
snap/hooks/install
snap/snapcraft.yaml

Notary will not only be used in the Juju ecosystem and having a snap for it will help make notary accessible to more users. This will also be necessary for the (potential) follow-up HSM story.
This PR depends on:
-  ~~#65 being merged first~~
- ~~The snap name being registered. It is now pending review because `notary` is a reserved name. Reference [here](https://forum.snapcraft.io/t/register-notary-snap-name/41883).~~
- ~~Add workflow to build and publish snap~~
- ~~Add snapcraft credentials to secrets~~

feat: add a snap for notary

---

.github/workflows/main.yml
.github/workflows/publish-snap.yaml

Publishing to the snap store fails right now and this PR "should" fix this issue.

fix: inherit secrets in publish-snap workflow

---

cmd/notary/main_test.go
internal/api/handlers.go
internal/api/handlers_test.go
internal/api/server.go
internal/api/server_test.go
internal/config/config.go
internal/config/config_test.go
internal/db/db.go
internal/db/db_test.go
internal/db/validation.go
internal/db/validation_test.go
internal/metrics/metrics.go
internal/metrics/metrics_test.go

This PR does a couple of things related to the database. Those are mainly because the database is no only used for certificate management anymore, it also stores users and soon Certificate Authority content.
- Rename the file from `certdb` to `db`
- Treat the certificateRequest and users table in the same way. Both are now un-parametrized and variables are used to referenced to both table names.
- Rename `CertificateRequestsRepository` to `Database` to reflect that the db contains varying types of data.

chore: generalise database management

---

.github/dependabot.yml

Run dependabot for npm dependencies (in addition to `go` and `github actions`).

chore: run dependabot for npm dependencies

---

cmd/notary/main_test.go
internal/config/config_test.go
internal/server/server_test.go

Include `err` value in test errors.
Here we address one of the major concerns from Ben review's (#84 ).

chore: include err value in test errors

---

.github/workflows/snap-publish.yaml

Use new repo for snap publish action.
Our CI is failing at the `snap-publish` step because the repo was moved from `snapcore` to `canonical` and the git tags were removed from the old one.

chore: use new repo for snap publish action

---

internal/server/handlers_accounts.go
internal/server/handlers_accounts_test.go

Ben's feedback included strong warning against password generation. Here we take those into account and remove the ability for Notary to generate passwords.

revert: remove password generation

---

.github/workflows/rock-publish.yaml

Fixes an issue with rock publishing where the version used to be taken from the `version` key in rockcraft.yaml. We now take the version fro the VERSION file.

fix: take version from version file

---

ui/src/app/nav.test.tsx
ui/src/app/nav.tsx
ui/src/app/types.ts

Display the Notary version in the UI leveraging the new /status endpoint.
Fixes #66

feat: display version in UI

---

ui/src/app/nav.tsx

This change modifies the version query from useEffect to react-query. This allows us to have some extra error protection if the call fails and also avoid sending a request every time the UI is rerendered.

chore: use react query for getting version

---

.github/workflows/rock-build.yaml
internal/server/handlers_certificate_requests.go
internal/server/handlers_certificate_requests_test.go
ui/src/app/queries.ts

Here we address 2 related issues.
1. The UI uses `certificate` instead of `cert` when creating certificates. This change was made in the Go webserver in a previous PR but we forgot to adapt the frontend.
2. The Go webserver now returns a "bad request" error when trying to create a certificate without the `certificate` parameter. It used to not check for required parameter and return a 201 created. 
3. The integration test in the github workflow uses the correct variable

fix: require certificate when creating certificates

---

.github/workflows/rock-scan.yaml

Use version from version file in rock-scan workflow as this is where the project version is now defined (instead of directly in rockcraft.yaml).

fix: use version from version file in rock-scan workflow

---

CONTRIBUTING.md
README.md

At the moment, the project's README.md serves as our official documentation. Here, we restructure the file so that it follows diataxis standards.
We also adapt the CONTRIBUTING.md to follow the same format with a clear and complete getting started tutorial.
- https://diataxis.fr/

docs: restructure following diataxis

---

internal/server/middleware.go
internal/server/response_controller.go

This change implements the response controller for the logging middleware as mentioned in #84.

feat: implement response controller for logging middleware

---

go.mod
go.sum
internal/db/db.go
internal/db/db_test.go
internal/metrics/metrics.go
internal/metrics/metrics_test.go
internal/server/authorization_test.go
internal/server/handlers_accounts.go
internal/server/handlers_accounts_test.go
internal/server/handlers_certificate_requests.go
internal/server/handlers_certificate_requests_test.go
internal/server/handlers_helpers_test.go
internal/server/handlers_login.go
internal/server/handlers_login_test.go
internal/server/handlers_status_test.go
internal/server/response.go
ui/package-lock.json
ui/src/app/(notary)/certificate_requests/table.test.tsx
ui/src/app/(notary)/certificate_requests/table.tsx
ui/src/types.ts

This change addresses the final points and closes #84, which modifies the database to have explicit ID's, adds a new status column and associated SQL checks, and utilizes SQLair to simplify database SQL calls.
It also changes the API of the database to fit the new way of using the status column. We now have functions that are abstracted from the direct SQL calls, like `UpdateCSR` -> `AddCertificateToCSR`. This is to simplify future development and help avoid getting the database into inconsistent states.
Another change that SQLair brings is the fact that it no longer returns the Result and LastID values that we used to pass along to the HTTP server. This means that successful API calls only receive a JSON message indicating success instead.

feat: replace pure SQL strings with SQLair

---

internal/server/handlers_accounts.go
internal/server/handlers_certificate_requests.go
internal/server/handlers_login.go
internal/server/handlers_status.go
internal/server/response.go

When using the writeHeader() function, go's net/http discards any other header that is set after this function call. This PR moves this function to the end of all of the handlers so we get the expected headers in our responses. To validate that this change works, we can use curl to look at the response headers.
Before the change:
```
< HTTP/2 401 
< content-type: text/plain; charset=utf-8
< content-length: 24
< date: Fri, 29 Nov 2024 20:02:31 GMT
```
The content type is text/plain because that is the default header attached to all handlers unless specified.
After the change:
```
< HTTP/2 401 
< content-type: application/json
< content-length: 24
< date: Fri, 29 Nov 2024 20:03:48 GMT
```
The correct content-type is set.

feat: add headers before writing headers

---

.github/workflows/main.yml
.github/workflows/rock-build.yaml
.github/workflows/rock-test.yaml

This change splits the steps that build and test the rock, which allows the workflow to upload the failed rock for debugging purposes.

chore: split rock build and test steps

---

.github/workflows/main.yml
.github/workflows/rock-build.yaml
.github/workflows/rock-test.yaml

The previous workflow change introduced a bug where we run the build step twice instead of running rock-build and rock-test. This PR fixes that.

ci: fix workflow

---

internal/server/server.go

We used to allow any TLS version in our HTTPs server. Here we only allow requests using TLS v1.2 and higher.
This addresses a HIGH severity warning from `gosec`
```shell
[/home/guillaume/code/notary/internal/server/server.go:65-67] - G402 (CWE-295): TLS MinVersion too low. (Confidence: HIGH, Severity: HIGH)
64:                 MaxHeaderBytes: 1 << 20,
> 65:                 TLSConfig: &tls.Config{
> 66:                         Certificates: []tls.Certificate{serverCerts},
> 67:                 },
68:         }
```

chore: set TLS minimum version to v1.2

---

internal/server/handlers_certificate_requests.go
internal/server/server.go

It was possible to call `SendPebbleNotification` with values that would trigger unwanted code execution. Example calling it with `key="abc" and request_id="1 && rm -rf /"`
```shell
pebble notify abc 1 && rm -rf /
```
While this was a risk at the local function level, I didn't see an obvious way to achieve it with our current API's since API handlers would make sure that the ID they received were ints. That being said, it's more secure to have the validation much closer to the actual exec call, which is what this PR does.

chore: prevent remote code execution in pebble calls

---

.github/workflows/go-lint.yaml

bump golangci-lint version in CI to `v1.63`

chore: bump golangci-lint version in CI

---

docs/tutorials/getting_started.md

Fix non-consecutive header levels that prevents the docs from building.
Our documentation should build and be published after this PR is merged.
```
python -m sphinx -T -W --keep-going -b dirhtml -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html  
Running Sphinx v8.[1](https://app.readthedocs.com/projects/canonical-notary/builds/2805088/#32069125--1).3
loading translations [en]... done
matplotlib is not installed, social cards will not be generated
making output directory... done
myst v4.0.1: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions={'linkify', 'substitution', 'deflist'}, disable_syntax=[], all_links_external=False, links_external_new_tab=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), …
```

docs: fix non-consecutive header levels

---

.github/workflows/go-lint.yaml
go.mod
internal/db/db_certificates.go
rockcraft.yaml
snap/snapcraft.yaml

Notary is still stuck in Go 1.22. Version 1.24 came out 3 days ago, so this PR updates Notary to that. It also includes a tiny change using a feature that was introduced in 1.23.

chore: update go version to 1.24

---

internal/db/db_certificate_authorities.go
internal/db/db_certificates.go
internal/db/db_csrs.go
internal/db/db_private_keys.go
internal/db/db_users.go
internal/db/filter.go
internal/server/handlers_accounts.go
internal/server/handlers_certificate_authorities.go
internal/server/handlers_certificate_requests.go
internal/server/handlers_login.go
internal/server/middleware.go
internal/server/server.go

This was a mistake from a while ago where I didn't know that all database connectors in go use int64 for ID fields. This change reflects that in our data structs.

chore: use int64 instead of int for DB ID fields

---

internal/db/db_certificate_authorities.go
internal/db/db_certificate_authorities_test.go
internal/server/handlers_accounts.go
internal/server/handlers_certificate_authorities.go
internal/server/handlers_certificate_authorities_test.go
internal/server/handlers_certificate_requests.go
internal/server/handlers_certificate_requests_test.go

We shouldn't return a 500 error code when the issue comes from the user input. The 400 Bad Request status code is more appropriate and informative in that context. Here, we add proper HTTP API input validation and return a relevant and informative status code when the input is invalid. For now, the changes have only been made for the CA endpoints. Once this PR is approved and merged, I will apply the same approach for all of our endpoints. 
Fixes #170 
Fixes #172 
Here we have the before and after returns when making a PUT call to change the status of a Certificate Authority. 
**Before**
```
Status: 500 Internal error
Response:
{
"error": "Internal Error"
}
```
**After**
```
Status: 400 Bad Request
Response:
{
"error": "Invalid request: invalid status: status must be one of active, …
```

feat: add API input validation and return appropriate HTTP status code

---

internal/server/handlers_accounts.go
internal/server/handlers_accounts_test.go
internal/server/handlers_certificate_requests.go
internal/server/handlers_certificate_requests_test.go

This PR applies the same changes as in #175 to the remaining endpoints (`accounts` and `certificate_requests`). We add input validation and avoid returning 500 error messages when receiving bad requests.

feat: add input validation for accounts and certificate requests endpoints

---

internal/db/db.go
internal/db/db_certificate_authorities.go
internal/db/db_certificates.go
internal/db/db_csrs.go
internal/db/db_private_keys.go
internal/db/db_users.go

This PR removes the ability to dynamically set table names. As more and more complex SQL queries are required, the amount of `Sprintf` magic required increases exponentially. Since we don't expect users to clone and change the table names or interact with the table directly at all, we should prioritise developer experience and get rid of these so we can write complex SQL queries easier.

chore: use static table names

---

internal/db/db_certificate_authorities_test.go
internal/db/db_certificates.go

The reason fixes #176 happens is because we have an infinite loop where a certificate refers to itself if it is self signed. We usually store self signed certificates in the database so that they refer to no certificate instead of their own ID in the database in order to avoid this issue, since we can infer that all certificates without parents are self signed.

fix: infinite certificate loop

---

internal/server/server_test.go

This quirk has been nagging me for a while where one of the tests don't use a tempdir so I have a rouge `certs.db` file in my folder every time i run this test

chore: update test to use tempdir

---

.github/workflows/go-sec.yaml
internal/config/config.go
internal/server/server.go

Here we add vulnerabiltiy scanning using `gosec` which is an helpful tool in finding common vulnerabilities. For instance, I used it to identify and address those issues:
- https://github.com/canonical/notary/commit/bf18cac429c46553cf7552860c777ee71a9a5d0b
- https://github.com/canonical/notary/commit/48d38e516965f337a2aca4ef9e3222b46cf734dc
Gosec is a well-known, widely used go security code scanner. 
Gosec can ignore some issues, and you will see two instances of those ignores added to our code base. Here are the gosec warnings:
```
[/home/guillaume/code/notary/internal/config/config.go:31] - G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
30:         config := Config{}
> 31:         configYaml, err := os.ReadFile(filePath)
32:         if err != …
```

chore: add gosec security scanning

---

docs/reference/api/accounts.md
docs/reference/api/certificate_authorities.md
docs/reference/api/certificate_requests.md
internal/db/db_certificate_authorities.go
internal/db/db_certificate_authorities_test.go
internal/db/db_certificates.go
internal/db/db_certificates_test.go
internal/db/db_csrs.go
internal/db/db_csrs_test.go
internal/db/db_private_keys.go
internal/db/db_private_keys_test.go
internal/db/db_test.go
internal/db/db_users.go
internal/db/db_users_test.go
internal/metrics/metrics_test.go
internal/server/handlers_accounts.go
internal/server/handlers_certificate_authorities.go
internal/server/handlers_certificate_requests.go
internal/server/response.go

This change reintroduces the last inserted id parameter, but only to create type functions. Previously, I had determined that this value did not update if we did updates or deletes in SQL, which made the functions confusing. Since then I've learned how this value is populated (it always contains the last inserted id, even if an irrelevant SELECT or UPDATE statement was the actual SQL statement that ran), and have decided to reintroduce it to reduce complexity in parts of the code where we'd have to immediately query for rows we had just inserted because we didn't have a way to know the last inserted ID's.

feat: return last inserted id for create type functions

---

.github/workflows/rock-test.yaml
CONTRIBUTING.md
docs/reference/config_file.md
internal/config/config_test.go
internal/db/db_test.go
internal/server/server_test.go
service/notary.yaml

The database name was misleading as it not only contains certs but everything persistent in Notary. Here I renamed the database from `certs.db` to the more appropriate `notary.db`.

chore: rename db to notary.db

---

docs/.wordlist.txt
docs/reference/api/index.md

Document the definition of Notary resources. For now this only includes:
- **Certificate Authorities**: Represents a Notary-owned Certificate Authority. Notary users can use Certificate Authorities to sign certificate requests for external entities.
- **Certificate Requests**: Represents a certificate request made by an external entity.
@ghislainbourgeois , @kayra1 , and I had an internal discussion around the various Notary resources and their meaning. We came to an agreement:
- Base level endpoints (ex. `/certificate_requests`) represent Notary resources
- The definition of those resources should be documented

docs: add Notary resource descriptions

---

.github/workflows/rock-publish.yaml

This change removes pushing the rock images to the registry alone, and instead pushes the single manifest list only. It's simpler.

chore: don't publish manifests separately

---

go.mod
go.sum
internal/server/handlers_login.go
internal/server/handlers_login_test.go
internal/server/middleware.go

We were using an old version of jwt, released in 2021. Here we bump jwt to the latest stable release and make the necessary changes to adapt to the lib's new API's.

chore: bump jwt version

---

internal/db/db_users.go
internal/db/db_users_test.go
internal/db/validation.go
internal/hashing/argon2id.go
internal/hashing/argon2id_test.go
internal/server/handlers_login.go

This PR replaces the use of `bcrypt` by `argon2id` as recommended by [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#password-hashing-algorithms). It uses the default parameters recommended by the same organization and creates a struct that can be used in the future to configure the parameters.
Because the Go library for `argon2id` is less complete than `bcrypt`, I also had to implement the salt generation, and the PHC formatting.
I took the opportunity to refactor a bit the login operation, so that when a user is not found, we still hash the password, so that an attacker cannot extract information about existing users by analyzing the timing.

feat: Use argon2id for password hashing as recommended by OWASP

---

internal/db/utils.go
internal/metrics/metrics.go
internal/metrics/metrics_test.go

This PR adds the following metrics:
- active_ca_certificate_validity_days: Number of days before the active CA certificate expires
- active_ca_certificates: Number of active CA Certificates
- legacy_ca_certificates: Number of legacy CA certificates
- pending_ca_certificates: Number of pending CA certificates
- expired_ca_certificates: Number of expired CA certificates
At the moment Notary allows having multiple active or pending CAs, the metrics will reflect that for now.

feat: Add CA metrics

---

internal/db/db_certificate_authorities.go
internal/server/handlers_certificate_authorities_test.go

When revoking a leaf cert the status of the the issuer's cert should not be changed, but when a CA is revoked, its state should become "legacy"

fix: Fixes CA status setting when revoking certs

---

internal/db/db_certificate_authorities.go
internal/db/db_certificate_authorities_test.go

Remove the CSR and private key when removing a CA

fix: remove CSR and private key when removing CA

---

internal/db/db_certificate_authorities.go
internal/server/handlers_certificate_authorities.go
internal/server/handlers_certificate_authorities_test.go
ui/src/app/(notary)/certificate_authorities/asideForm.tsx
ui/src/app/(notary)/certificate_authorities/components.tsx
ui/src/app/(notary)/certificate_authorities/page.tsx
ui/src/app/(notary)/certificate_authorities/table.tsx
ui/src/app/(notary)/certificate_requests/table.tsx
ui/src/components/NotaryAppNavigationBars.tsx
ui/src/components/NotaryConfirmationModal.tsx
ui/src/globals.scss
ui/src/hooks/useAuth.tsx
ui/src/queries.ts
ui/src/types.ts
ui/src/utils.ts
ui/src/validators.ts

This PR introduces a new page to the frontend where the new CA API changes can be used. It includes all of the required features for CA management and signing except for revoking all sub-certificates.

feat: certificate authority management page

---

.github/workflows/main.yml
.github/workflows/tics.yaml

I thought tics installed its own dependencies. but it doesn't. it also doesn't error out if it's missing, it just tanks the score of the repo instead.

ci: add tics dependency

---

.gitignore
Makefile

This change introduces a makefile that will create notary, create default config files for notary, and deploy it as a docker image in a lxd vm, just like how nms works. In future PR's, we can add a dev mode to the UI and deploy the observability stack to quickly test changes to those features like dashboards, new metrics, traces and audit logs.

feat: makefile

---

internal/db/db.go
internal/db/db_certificate_authorities.go
internal/db/db_certificates.go
internal/db/db_csrs.go
internal/db/db_private_keys.go
internal/db/db_users.go
internal/db/filter.go
internal/db/sql_stmts.go
internal/db/utils.go

This change moves the constant sql statements into its own file, and prepares all of them during startup instead of on-demand. This removes a lot of the unnecessary error checks that are guaranteed to succeed forever if they are compiled the first time.

chore: reorganize sql statements

---

docs/reference/api/login.md

The `login` api path was incorrectly documented. Here we replace `/api/v1/login` with `/login` in the API reference.
Fixes #244

docs: correct login path

---

ui/src/app/(notary)/certificate_requests/asideForm.tsx

Given an existing CSR in Notary, when users made an identical request using the UI, Notary wouldn't show them why the request failed. The error message from the backend never made its way to the user. Here we address this issue using `type="button`, which prevents the <Button> inside a <form> from triggering a native form submission.
Fixes #231

fix: inform users when backend rejected request [ui]

---

ui/src/app/(notary)/users/page.tsx
ui/src/utils.ts

Given a non-admin user, when they try to access a page they are forbidden to access, they are currently seeing a loading component. Here we replace the existing behavior with a clear "forbidden" message making it obvious why the page doesn't load normally.
Fixes #82

feat: display 403 page when user tries to access forbidden page

---

docs/reference/api/certificate_requests.md
internal/db/db_certificate_authorities.go
internal/db/db_certificate_authorities_test.go
internal/db/db_certificates_test.go
internal/db/db_csrs.go
internal/db/db_csrs_test.go
internal/db/db_init_test.go
internal/db/sql_stmts.go
internal/db/types.go
internal/metrics/metrics_test.go
internal/server/handlers_certificate_authorities.go
internal/server/handlers_certificate_requests.go
internal/server/handlers_certificate_requests_test.go
ui/src/app/(notary)/certificate_requests/table.tsx
ui/src/types.ts

Here we map certificate requests to users, making it clear to certificate administrators who requested which certificate. This feature is valuable on its own and as part of adding authorization support to Notary. This includes changes at the database, API, and UI levels.
We added `username` as a return attribute when retrieving certificate requests `GET https://127.0.0.1:3001/api/v1/certificate_requests/1`
```
{
"result": {
"id": 1,
"csr": "-----BEGIN CERTIFICATE REQUEST-----\nMIIC6TCCAdECAQAwcjELMAkGA1UEBhMCQ0ExCzAJBgNVBAgMAlFDMRIwEAYDVQQH\nDAlNb250csOpYWwxFzAVBgNVBAoMDkNhbm9uaWNhbCBMdGQuMRcwFQYDVQQLDA5D\nYW5vbmljYWwgTHRkLjEQMA4GA1UEAwwHZGRkLmNvbTCCASIwDQYJKoZIhvcNAQEB\nBQADggEPADCCAQoCggEBALb0EezLypyljI1c+prNLIqyOMGJ8U5M85HutF2vy5vs\nYH9WFWkYbXto7M18BKLRHJ1AA9WFeNFGyYwsu+2RESYTCUrTGh2RFl …
```

feat: map certificate requests to users

---

.github/workflows/main.yml
.github/workflows/tics.yaml

Following a TICS upgrade, all workflows using Go have to update the ‘viewerUrl’ to 'https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=GoProjects'. This should fix an issue with our workflow currently not working. 
- https://chat.canonical.com/canonical/pl/w76d5zmx4id7bxrwszsx5cxsme

fix: use GoProjects viewer url in TICS workflow

---

docs/.wordlist.txt
docs/explanation/security.md
docs/reference/api/accounts.md
docs/reference/index.md
docs/reference/roles.md
internal/db/db_csrs.go
internal/db/db_csrs_test.go
internal/db/db_users_test.go
internal/db/filter.go
internal/db/sql_stmts.go
internal/db/types.go
internal/db/validation.go
internal/server/authorization.go
internal/server/authorization_test.go
internal/server/handlers_accounts_test.go
internal/server/handlers_certificate_authorities_test.go
internal/server/handlers_certificate_requests.go
internal/server/handlers_certificate_requests_test.go
internal/server/handlers_config_test.go
internal/server/handlers_login_test.go
internal/server/handlers_status_test.go
internal/server/router.go
internal/server/server_test.go
internal/testutils/server_test_utils.go
ui/src/app/(notary)/certificate_authorities/table.tsx
ui/src/app/(notary)/certificate_requests/table.tsx
ui/src/app/(notary)/users/asideForm.tsx
ui/src/app/(notary)/users/table.tsx
ui/src/components/NotaryAppNavigationBars.tsx
ui/src/types.ts

In #257 and #261, we added the necessary structure to support roles and permissions in Notary, we added the ability to choose and view user roles. 
In this PR here, we add the remaining roles needed for Notary to be useful in an enterprise. We now support the following roles:
- **Admin**: Full access to all Notary features.
- **Certificate Manager**: Can manage Certificate Authorities, Certificate Requests, issue and revoke certificates.
- **Certificate Requestor (new)**: Can create Certificate Requests and view their own requests.
- **Read Only (new)**: Can read everything except accounts.
This task is an implementation of the [TE197 - Role-based access in Notary](https://docs.google.com/document/d/1j3Jq9K4W_Jpouw5wNGqoXUOcHafjBu9H6PTgUqQcsIQ/edit?tab=t.0) specification.
Add new roles …

feat: add certificate requester and readonly roles
